version: '3.8'

services:
  traffic-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    environment:
      - PYTHONPATH=/app
      - AWS_DEFAULT_REGION=ap-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - LOCAL_MODE=true
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - pip-cache:/root/.cache/pip
    restart: unless-stopped

volumes:
  pip-cache: